# Generated by Django 3.0.5 on 2020-04-08 10:46

import datetime
from django.db import migrations, models
import flask_login.mixins
import instagram.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.CharField(max_length=255, validators=[instagram.models.user.UserValidation.validate_length])),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, validators=[instagram.models.user.UserValidation.validate_regex])),
            ],
            options={
                'db_table': 'user',
            },
            bases=(flask_login.mixins.UserMixin, models.Model),
        ),
    ]
