# Generated by Django 3.0.5 on 2020-04-08 22:49

from django.db import migrations, models
import instagram.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[instagram.models.user.UserValidation.validate_length]),
        ),
    ]
