# Generated by Django 3.0.5 on 2020-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
