# Generated by Django 3.0.5 on 2020-04-12 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20200412_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='instagram.User')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='instagram.Image')),
            ],
            options={
                'db_table': 'donation',
            },
        ),
    ]
