# Generated by Django 3.0.5 on 2020-04-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_auto_20200419_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='profile_url',
        ),
    ]
