# Generated by Django 3.0.5 on 2020-04-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_auto_20200420_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_url',
            new_name='profile_image',
        ),
    ]
