# Generated by Django 3.0.5 on 2020-04-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_rename_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='image_url',
        ),
    ]
